// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"database/sql"
)

type BusStop struct {
	ID        int32           `json:"id"`
	Name      string          `json:"name"`
	Lat       sql.NullFloat64 `json:"lat"`
	Lng       sql.NullFloat64 `json:"lng"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}
