// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateBusStop(ctx context.Context, arg CreateBusStopParams) (BusStop, error)
	DeleteBusStop(ctx context.Context, id int32) error
	GetBusStop(ctx context.Context, id int32) (BusStop, error)
	ListBusStops(ctx context.Context) ([]BusStop, error)
	UpdateBusStop(ctx context.Context, arg UpdateBusStopParams) error
}

var _ Querier = (*Queries)(nil)
