version: 2.1

jobs:
  spec:
    docker:
      - image: cimg/node:22.15.1
    steps:
      - checkout
      - restore_cache:
        name: Restore caches.
        key: spec-pnpm-deps-{{ checksum "./pnpm-lock.lock" }}
      - run:
        name: pnpm install
        working_directory: spec
        command: pnpm install
      - run:
        name: pnpm lint
        working_directory: spec
        command: pnpm lint
      - run:
        name: pnpm build
        working_directory: spec
        command: pnpm build
      - save_cache:
        name: Save caches.
        paths:
          - ./spec/node_modules
        key: spec-pnpm-deps-{{ checksum "./pnpm-lock.lock" }}

  web:
    docker:
      - image: cimg/node:22.15.1
    steps:
      - checkout
      - restore_cache:
        name: Restore caches.
        key: web-pnpm-deps-{{ checksum "./pnpm-lock.lock" }}
      - run:
        name: pnpm install
        working_directory: web
        command: pnpm install
      - run:
        name: pnpm lint
        working_directory: web
        command: pnpm lint
      - run:
        name: pnpm build
        working_directory: web
        command: yarn build
      - run:
        name: pnpm start
        working_directory: web
        background: true
        command: pnpm start
      - save_cache:
        name: Save caches.
        paths:
          - ./web/node_modules
        key: web-pnpm-deps-{{ checksum "./pnpm-lock.lock" }}

workflows:
  build:
    - spec
    - web:
      requires:
        - spec
