version: 2.1

jobs:
  spec:
    docker:
      - image: cimg/node:22.15.1
    steps:
      - checkout

      - restore_cache:
          name: Restore spec cache
          keys:
            - spec-pnpm-deps-{{ checksum "./pnpm-lock.lock" }}

      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-10 --activate
            pnpm config set store-dir ~/.cache/pnpm

      - run:
          name: Install dependencies
          working_directory: spec
          command: pnpm install

      - run:
          name: Lint
          working_directory: spec
          command: pnpm lint

      - run:
          name: Build
          working_directory: spec
          command: pnpm build

      - save_cache:
          name: Save spec cache
          key: spec-pnpm-deps-{{ checksum "./pnpm-lock.yaml" }}
          paths:
            - ./spec/node_modules

  web:
    docker:
      - image: cimg/node:22.15.1
    steps:
      - checkout

      - restore_cache:
          name: Restore web cache
          keys:
            - web-pnpm-deps-{{ checksum "./pnpm-lock.lock" }}

      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-10 --activate
            pnpm config set store-dir ~/.cache/pnpm

      - run:
          name: Install dependencies
          working_directory: web
          command: pnpm install

      - run:
          name: Lint
          working_directory: web
          command: pnpm lint

      - run:
          name: Build
          working_directory: web
          command: yarn build

      - run:
          name: Start in background
          working_directory: web
          background: true
          command: pnpm start

      - save_cache:
          name: Save web cache
          key: web-pnpm-deps-{{ checksum "./pnpm-lock.yaml" }}
          paths:
            - ./web/node_modules

workflows:
  version: 2
  build:
    jobs:
      - spec
      - web:
          requires:
            - spec
