steps:
  - name: 'golang:1.24.1'
    id: 'Build Go binary'
    dir: 'apps/api'
    entrypoint: 'go'
    args: ['build', '-o', 'api_server', './cmd/server']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy binary'
    args:
      - compute
      - scp
      - /workspace/apps/api/api_server
      - "tut-bus-api:/tmp/api_server"
      - --zone
      - "us-central1-c"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy, git pull, and restart service'
    args:
      - compute
      - ssh
      - "tut-bus-api"
      - --zone
      - "us-central1-c"
      - --command
      - |
        cd /opt/tut-bus/apps/api && \
        git checkout main && \
        git pull origin main && \
        sudo mv /tmp/api_server /opt/tut-bus/apps/api/api_server && \
        sudo chown tut-bus:nogroup /opt/tut-bus/apps/api/api_server && \
        sudo chmod 755 /opt/tut-bus/apps/api/api_server && \
        sudo systemctl restart tut-bus
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET