steps:
  - name: 'golang:1.24.1'
    id: 'Build Go binary'
    dir: 'apps/api'
    entrypoint: 'go'
    args: ['build', '-o', 'api_server', './cmd/server']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload to GCS'
    args:
      - cp
      - /workspace/apps/api/api_server
      - gs://tut-bus-prod-binaries/api_server

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Download-and-deploy'
    args:
      - compute
      - ssh
      - 'tut-bus-api'
      - --zone=us-central1-c
      - --command
      - |
        gsutil cp gs://tut-bus-prod-binaries/api_server /tmp/api_server && \
        chmod +x /tmp/api_server && \
        sudo mv /tmp/api_server /opt/tut-bus/apps/api/api_server && \
        sudo systemctl restart tut-bus
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
